# Generated by Django 5.2.1 on 2025-06-01 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='last_updated',
            new_name='updated_at',
        ),
        migrations.AlterField(
            model_name='product',
            name='price_str',
            field=models.CharField(max_length=50),
        ),
    ]
