# Generated by Django 5.2.1 on 2025-06-01 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_rename_last_updated_product_updated_at_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
