# Generated by Django 5.2.1 on 2025-06-01 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_product_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='target_price',
            field=models.FloatField(default=0.0),
        ),
    ]
